use serde::{Deserialize, Serialize};

use crate::math::bbox::AABB;
use crate::math::transform::Transform2D;
use crate::model::canvas::NodeId;
use crate::model::stroke::{Color, Stroke};

/// Backend-agnostic drawing primitives generated by the rendering pipeline.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum RenderCommand {
    /// Sets or intersects hardware/software scissor clipping rect in screen pixels.
    PushScissor {
        screen_rect: AABB,
    },
    /// Restores previous scissor clipping rect.
    PopScissor,
    /// Draws the background and border of a sub-canvas container.
    DrawCanvasBackground {
        node_id: NodeId,
        screen_rect: AABB,
        fill_color: Color,
        border_color: Color,
        border_width: f32,
    },
    /// Draws a vector stroke with the given coordinate transformation applied.
    DrawStroke {
        stroke: Stroke,
        transform: Transform2D,
    },
}

/// A sequential queue of render commands ready for native GPU (WGPU/Tauri/OpenGL) execution.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct RenderQueue {
    pub commands: Vec<RenderCommand>,
    pub stats: RenderStats,
}

/// Telemetry metrics for render frame efficiency and spatial culling.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct RenderStats {
    pub total_nodes: usize,
    pub rendered_nodes: usize,
    pub culled_nodes: usize,
    pub total_strokes: usize,
    pub rendered_strokes: usize,
    pub culled_strokes: usize,
}

impl RenderQueue {
    pub fn new() -> Self {
        Self {
            commands: Vec::new(),
            stats: RenderStats::default(),
        }
    }

    #[inline]
    pub fn push(&mut self, command: RenderCommand) {
        self.commands.push(command);
    }
}
