use glam::Vec2;
use serde::{Deserialize, Serialize};

use crate::event::input::{InputEvent, PointerButton};
use crate::math::transform::Camera;
use crate::model::canvas::NodeId;
use crate::model::point::Point2D;
use crate::model::scene::SceneGraph;
use crate::model::stroke::{BrushType, Color};

/// Eraser operating mode.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub enum EraserMode {
    /// Object-level eraser (deletes entire stroke on contact).
    Object,
    /// Segment eraser (splits stroke at contact points).
    Segment,
}

/// Active interaction tool.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum Tool {
    Select,
    Pan,
    Draw {
        brush_type: BrushType,
        color: Color,
        width: f32,
    },
    Eraser {
        mode: EraserMode,
        radius: f32,
    },
}

impl Default for Tool {
    fn default() -> Self {
        Self::Draw {
            brush_type: BrushType::Solid,
            color: Color::BLACK,
            width: 3.0,
        }
    }
}

/// High-level action output generated by controller after processing input.
#[derive(Debug, Clone, PartialEq)]
pub enum ControllerAction {
    None,
    RedrawRequired,
    StrokeStarted {
        target_node: NodeId,
        point: Point2D,
        brush_type: BrushType,
        color: Color,
        width: f32,
    },
    StrokeAppended {
        target_node: NodeId,
        point: Point2D,
    },
    StrokeFinished {
        target_node: NodeId,
    },
    EraseRequested {
        target_node: NodeId,
        local_pos: Vec2,
        mode: EraserMode,
        radius: f32,
    },
}

/// Manages interactive viewport navigation (pan/zoom) and active tool routing.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CanvasController {
    pub camera: Camera,
    pub tool: Tool,
    pub is_panning: bool,
    pub last_screen_pos: Option<Vec2>,
    pub active_draw_node: Option<NodeId>,
    pub min_zoom: f32,
    pub max_zoom: f32,
}

impl Default for CanvasController {
    fn default() -> Self {
        Self::new(Camera::default(), Tool::default())
    }
}

impl CanvasController {
    pub fn new(camera: Camera, tool: Tool) -> Self {
        Self {
            camera,
            tool,
            is_panning: false,
            last_screen_pos: None,
            active_draw_node: None,
            min_zoom: 0.05,
            max_zoom: 64.0,
        }
    }

    /// Zooms the camera around a screen anchor point (e.g. cursor position),
    /// keeping the world coordinate under the cursor invariant.
    pub fn zoom_at_anchor(&mut self, anchor_screen: Vec2, factor: f32) {
        if factor <= 0.0 || (factor - 1.0).abs() < 1e-6 {
            return;
        }

        // 1. Get world coordinate under cursor before zoom
        let world_anchor = self.camera.screen_to_world(anchor_screen);

        // 2. Update zoom factor within bounds
        let new_zoom = (self.camera.zoom * factor).clamp(self.min_zoom, self.max_zoom);
        self.camera.zoom = new_zoom;

        // 3. Adjust camera pan so world_anchor maps to anchor_screen after zoom
        let screen_center = Vec2::new(
            self.camera.viewport_width * 0.5,
            self.camera.viewport_height * 0.5,
        );
        let offset_from_center = anchor_screen - screen_center;
        self.camera.pan = world_anchor - (offset_from_center / self.camera.zoom);
    }

    /// Pans the camera by screen pixel delta `(dx, dy)`.
    pub fn pan_by_screen_delta(&mut self, screen_delta: Vec2) {
        self.camera.pan -= screen_delta / self.camera.zoom;
    }

    /// Main event handler routing events to pan/zoom or active tool actions.
    pub fn handle_event(&mut self, scene: &SceneGraph, event: &InputEvent) -> ControllerAction {
        match event {
            InputEvent::Wheel {
                screen_pos,
                delta_y,
                modifiers,
                ..
            } => {
                if modifiers.ctrl {
                    // Zoom with Ctrl + Wheel
                    let factor = if *delta_y < 0.0 { 1.15 } else { 1.0 / 1.15 };
                    self.zoom_at_anchor(*screen_pos, factor);
                } else {
                    // Pan with normal wheel
                    self.pan_by_screen_delta(Vec2::new(0.0, -delta_y));
                }
                ControllerAction::RedrawRequired
            }
            InputEvent::PinchGesture {
                screen_anchor,
                scale_delta,
            } => {
                self.zoom_at_anchor(*screen_anchor, *scale_delta);
                ControllerAction::RedrawRequired
            }
            InputEvent::Resize { width, height } => {
                self.camera.viewport_width = width.max(1.0);
                self.camera.viewport_height = height.max(1.0);
                ControllerAction::RedrawRequired
            }
            InputEvent::PointerDown {
                screen_pos,
                button,
                pressure,
                modifiers,
                timestamp,
                ..
            } => {
                self.last_screen_pos = Some(*screen_pos);

                // Spacebar + drag OR middle click initiates viewport panning
                if *button == PointerButton::Middle || modifiers.space || self.tool == Tool::Pan {
                    self.is_panning = true;
                    return ControllerAction::RedrawRequired;
                }

                if *button == PointerButton::Primary {
                    match self.tool {
                        Tool::Draw {
                            brush_type,
                            color,
                            width,
                        } => {
                            let (target_node, local_pos) =
                                scene.hit_test_screen(&self.camera, *screen_pos);
                            self.active_draw_node = Some(target_node);
                            let pt = Point2D::new(local_pos.x, local_pos.y, *pressure, *timestamp);
                            return ControllerAction::StrokeStarted {
                                target_node,
                                point: pt,
                                brush_type,
                                color,
                                width,
                            };
                        }
                        Tool::Eraser { mode, radius } => {
                            let (target_node, local_pos) =
                                scene.hit_test_screen(&self.camera, *screen_pos);
                            return ControllerAction::EraseRequested {
                                target_node,
                                local_pos,
                                mode,
                                radius: radius / self.camera.zoom, // scale radius to world/local units
                            };
                        }
                        _ => {}
                    }
                }
                ControllerAction::None
            }
            InputEvent::PointerMove {
                screen_pos,
                pressure,
                timestamp,
                ..
            } => {
                let delta = if let Some(last) = self.last_screen_pos {
                    *screen_pos - last
                } else {
                    Vec2::ZERO
                };
                self.last_screen_pos = Some(*screen_pos);

                if self.is_panning {
                    self.pan_by_screen_delta(delta);
                    return ControllerAction::RedrawRequired;
                }

                if let Some(active_node) = self.active_draw_node {
                    if let Ok(world_transform) = scene.compute_world_transform(active_node) {
                        if let Ok(local_pos) = self
                            .camera
                            .screen_to_child_local(*screen_pos, &world_transform)
                        {
                            let pt =
                                Point2D::new(local_pos.x, local_pos.y, *pressure, *timestamp);
                            return ControllerAction::StrokeAppended {
                                target_node: active_node,
                                point: pt,
                            };
                        }
                    }
                } else if let Tool::Eraser { mode, radius } = self.tool {
                    if let Some(PointerButton::Primary) = None::<PointerButton> {
                        // handled on move if dragging eraser
                    }
                    let (target_node, local_pos) =
                        scene.hit_test_screen(&self.camera, *screen_pos);
                    return ControllerAction::EraseRequested {
                        target_node,
                        local_pos,
                        mode,
                        radius: radius / self.camera.zoom,
                    };
                }
                ControllerAction::None
            }
            InputEvent::PointerUp {
                button, ..
            } => {
                self.last_screen_pos = None;
                if *button == PointerButton::Middle || self.is_panning {
                    self.is_panning = false;
                    return ControllerAction::RedrawRequired;
                }

                if let Some(target_node) = self.active_draw_node.take() {
                    return ControllerAction::StrokeFinished { target_node };
                }
                ControllerAction::None
            }
            InputEvent::PointerLeave => {
                self.last_screen_pos = None;
                self.is_panning = false;
                if let Some(target_node) = self.active_draw_node.take() {
                    return ControllerAction::StrokeFinished { target_node };
                }
                ControllerAction::None
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::event::input::PointerDevice;
    use crate::math::transform::Transform2D;
    use crate::model::canvas::CanvasNode;
    use approx::assert_relative_eq;

    #[test]
    fn test_zoom_around_anchor_invariance() {
        let mut controller = CanvasController::default();
        let cursor_screen = Vec2::new(300.0, 400.0);

        let world_before = controller.camera.screen_to_world(cursor_screen);

        // Zoom 2x around cursor position
        controller.zoom_at_anchor(cursor_screen, 2.0);

        let world_after = controller.camera.screen_to_world(cursor_screen);

        // World coordinate under cursor MUST be unchanged
        assert_relative_eq!(world_before.x, world_after.x, epsilon = 1e-3);
        assert_relative_eq!(world_before.y, world_after.y, epsilon = 1e-3);
    }

    #[test]
    fn test_draw_routing_to_nested_canvas() {
        let mut scene = SceneGraph::new();
        let root_id = scene.root_id();

        // Subcanvas at (200, 200)
        let sub = CanvasNode::new(
            "Sub",
            400.0,
            400.0,
            Transform2D::from_translation(Vec2::new(200.0, 200.0)),
        );
        let sub_id = sub.id;
        scene.insert_child(root_id, sub).unwrap();

        let mut controller = CanvasController::default();
        controller.camera = Camera::new(Vec2::new(200.0, 200.0), 1.0, 1000.0, 1000.0);

        // Screen (500, 500) corresponds to world (200, 200) which is local (0, 0) of sub
        let down_event = InputEvent::PointerDown {
            screen_pos: Vec2::new(550.0, 550.0), // world (250, 250) -> local (50, 50) of sub
            button: PointerButton::Primary,
            pressure: 0.75,
            device: PointerDevice::Stylus,
            modifiers: Default::default(),
            timestamp: 100,
        };

        let action = controller.handle_event(&scene, &down_event);
        match action {
            ControllerAction::StrokeStarted {
                target_node,
                point,
                ..
            } => {
                assert_eq!(target_node, sub_id);
                assert_relative_eq!(point.x, 50.0);
                assert_relative_eq!(point.y, 50.0);
                assert_relative_eq!(point.pressure, 0.75);
            }
            _ => panic!("Expected StrokeStarted action"),
        }
    }
}
