use glam::Vec2;
use serde::{Deserialize, Serialize};

use crate::model::board::BoardId;
use crate::model::point::Point2D;
use crate::model::stage::StageState;
use crate::model::stroke::{BrushType, Color, Stroke};

/// Lifecycle phase of a hardware pointer event.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum PointerPhase {
    Down,
    Move,
    Up,
    Cancel,
}

/// Pointer mouse button.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum MouseButton {
    None,
    Primary,
    Secondary,
    Middle,
    Other(u16),
}

/// Raw hardware pointer event captured from window / viewport.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PointerEvent {
    pub id: u32,
    pub phase: PointerPhase,
    pub screen_pos: Vec2,
    pub pressure: f32,
    pub timestamp_ms: u64,
    pub button: MouseButton,
}

/// Transformation mode when dragging or resizing a sub-board window.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TransformMode {
    Move,
    ResizeTopLeft,
    ResizeTopRight,
    ResizeBottomLeft,
    ResizeBottomRight,
}

/// Finite State Machine (FSM) managing active stage interactions and target locks.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum InteractionState {
    /// Idle state waiting for user interaction.
    Idle,
    /// Drawing state: locked to a specific target sub-board.
    Drawing {
        target_board_id: BoardId,
        active_stroke: Stroke,
    },
    /// Erasing state: continuous stroke intersection querying.
    Erasing {
        target_board_id: BoardId,
        eraser_radius: f32,
    },
    /// Sub-board window manipulation (moving / resizing).
    BoardTransforming {
        board_id: BoardId,
        mode: TransformMode,
        initial_pos: Vec2,
    },
    /// Viewport stage panning.
    StagePanning {
        start_screen: Vec2,
        initial_camera_pan: Vec2,
    },
}

impl Default for InteractionState {
    fn default() -> Self {
        Self::Idle
    }
}

/// Outcome / Action generated by the interaction FSM event dispatcher.
#[derive(Debug, Clone, PartialEq)]
pub enum FsmAction {
    None,
    RedrawRequired,
    StrokeFinished {
        target_board_id: BoardId,
        stroke: Stroke,
    },
    StrokesErased {
        target_board_id: BoardId,
        local_pos: Vec2,
        radius: f32,
    },
    BoardMoved {
        board_id: BoardId,
        delta: Vec2,
    },
}

/// Interaction Event Dispatcher running the FSM on the stage.
#[derive(Debug, Default)]
pub struct EventDispatcher {
    pub state: InteractionState,
    pub current_brush_type: BrushType,
    pub current_brush_color: Color,
    pub current_brush_width: f32,
    pub current_eraser_radius: f32,
}

impl EventDispatcher {
    pub fn new() -> Self {
        Self {
            state: InteractionState::Idle,
            current_brush_type: BrushType::Solid,
            current_brush_color: Color::WHITE,
            current_brush_width: 3.0,
            current_eraser_radius: 16.0,
        }
    }

    /// Dispatches a pointer event through the Interaction FSM.
    ///
    /// Enforces **Target Locking Invariant**:
    /// When `PointerDown` locks `target_board_id`, subsequent `PointerMove` events remain strictly
    /// bound to that target board even if the cursor leaves the sub-board boundary.
    pub fn handle_pointer_event(
        &mut self,
        stage: &mut StageState,
        event: &PointerEvent,
    ) -> FsmAction {
        match event.phase {
            PointerPhase::Down => {
                // Middle click triggers stage panning
                if event.button == MouseButton::Middle {
                    self.state = InteractionState::StagePanning {
                        start_screen: event.screen_pos,
                        initial_camera_pan: stage.camera.pan,
                    };
                    return FsmAction::RedrawRequired;
                }

                if event.button == MouseButton::Primary {
                    if let Some((hit_board_id, local_pos)) = stage.hit_test_screen(event.screen_pos) {
                        let initial_pt = Point2D::new(
                            local_pos.x,
                            local_pos.y,
                            event.pressure,
                            event.timestamp_ms,
                        );

                        let stroke = Stroke::new(
                            vec![initial_pt],
                            self.current_brush_color,
                            self.current_brush_width,
                            self.current_brush_type,
                        );

                        // Lock target board
                        self.state = InteractionState::Drawing {
                            target_board_id: hit_board_id,
                            active_stroke: stroke,
                        };
                        return FsmAction::RedrawRequired;
                    } else {
                        // Clicking empty stage background triggers stage panning
                        self.state = InteractionState::StagePanning {
                            start_screen: event.screen_pos,
                            initial_camera_pan: stage.camera.pan,
                        };
                        return FsmAction::RedrawRequired;
                    }
                }
                FsmAction::None
            }

            PointerPhase::Move => {
                match &mut self.state {
                    InteractionState::Drawing {
                        target_board_id,
                        active_stroke,
                    } => {
                        // Target Locking: compute local position relative to locked target board
                        if let Some(board) = stage.get_board(*target_board_id) {
                            if let Ok(inv) = board.transform.inverse() {
                                let world_pt = stage.camera.screen_to_world(event.screen_pos);
                                let local_pt = inv.transform_point(world_pt);
                                let pt = Point2D::new(
                                    local_pt.x,
                                    local_pt.y,
                                    event.pressure,
                                    event.timestamp_ms,
                                );
                                active_stroke.push_point(pt);
                                return FsmAction::RedrawRequired;
                            }
                        }
                    }
                    InteractionState::Erasing {
                        target_board_id,
                        eraser_radius,
                    } => {
                        if let Some(board) = stage.get_board(*target_board_id) {
                            if let Ok(inv) = board.transform.inverse() {
                                let world_pt = stage.camera.screen_to_world(event.screen_pos);
                                let local_pt = inv.transform_point(world_pt);
                                return FsmAction::StrokesErased {
                                    target_board_id: *target_board_id,
                                    local_pos: local_pt,
                                    radius: *eraser_radius,
                                };
                            }
                        }
                    }
                    InteractionState::StagePanning {
                        start_screen,
                        initial_camera_pan,
                    } => {
                        let screen_delta = event.screen_pos - *start_screen;
                        stage.camera.pan = *initial_camera_pan - screen_delta / stage.camera.zoom;
                        return FsmAction::RedrawRequired;
                    }
                    _ => {}
                }
                FsmAction::None
            }

            PointerPhase::Up | PointerPhase::Cancel => {
                match std::mem::replace(&mut self.state, InteractionState::Idle) {
                    InteractionState::Drawing {
                        target_board_id,
                        active_stroke,
                    } => {
                        if active_stroke.points.len() >= 2 {
                            return FsmAction::StrokeFinished {
                                target_board_id,
                                stroke: active_stroke,
                            };
                        }
                    }
                    InteractionState::StagePanning { .. } => {
                        return FsmAction::RedrawRequired;
                    }
                    _ => {}
                }
                FsmAction::None
            }
        }
    }
}
